version: '3'

services:
   db:
    container_name: nodeapp_db
    build: docker/db
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - ./docker/db/data:/docker-entrypoint-initdb.d
      - db_nodeapp_data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/my.cnf
    env_file:
      - ./.env
   node:
    container_name: nodeapp
    build: docker/node
    tty: true
    volumes:
      - ./app:/home/app
    env_file:
      - ./.env
    ports:
      - '${APP_PORT}:80'
   redis:
    container_name: nodeapp_redis
    image: 'redis:latest'
    ports:
      - '${REDIS_PORT}:6379'
volumes:
  db_nodeapp_data: